CREATE TABLE users{
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(30) NOT NULL,
    sex VARCHAR(10),
    phone VARCHAR(10),
    password VARCHAR(30) NOT NULL
};