CREATE TABLE product(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(20),
price NUMERIC(10,2) NOT NULL,
description VARCHAR(255),
brand_id BIGINT NOT NULL,
category_id BIGINT NOT NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
is_active BOOLEAN DEFAULT TRUE,

CONSTRAINT fk_brand FOREIGN KEY (brand_id) REFERENCES brands(id),
CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES category(id)
);