spring.application.name=userApi_Application

# =========================================
# DATABASE
# =========================================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================
# SERVER
# =========================================

server.port=8082

# =========================================
# JPA / LIQUIBASE
# =========================================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# REMOVE THIS
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================================
# KEYCLOAK RESOURCE SERVER
# =========================================

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/user-api

# =========================================
# KEYCLOAK ADMIN CONFIG
# =========================================

keycloak.server-url=http://keycloak:8080

keycloak.realm=user-api

keycloak.admin.realm=master

keycloak.admin.username=admin

keycloak.admin.password=admin

#keycloak.client-id=admin-cli

keycloak.client-id=user-api-backend

keycloak.client-secret=user-api-secret-2026

# =========================================
# LOGGING
# =========================================

logging.level.org.springframework.security=DEBUG
logging.level.org.keycloak=DEBUG